py4cast/lightning.py, py4cast/observer.py
- Add new scalar to tensorboard that show the same scores as the scores cards, but as curves.
- They can be compared between several models
=> add tensorboard test scores per timestep

bin/test.py, bin/train.py
Add a profiler to the test "binary"
=> Profiling on test

py4cast/lightning.py, py4cast/metrics.py
Reccurrent bugs from tochmetrics in multigPU context (see #41 and #5)
See the referrred issues for stacktraces. The errors happen in multiGPU context, with the gather operation, triggering : 
`RuntimeError: No backend type associated with device type cpu`
The issue is that the metrics must be declared in the scope of the lightning module (and not in the "on_val/test_start" functions scope), to be effectively ported and calculated on multiple devices. So, it does not fail on cpu, nor on single-gpu context.
Moving these declarations in the lightninmodule init is needed.
=> fixing metrics behavior in a multiGPU context

README.md, env.yaml, env_conda.yaml
* adds missing conda dependencies
* adds documentation for PY4CAST_ROOTDIR
Tested on ECMWF ATOS with
```bash
srun --nodes=1 --qos=ng --gpus=1 --mem=256G --ntasks-per-node=1 --cpus-per-task=32 --time=5:00:00 --pty bash
export PY4CAST_ROOTDIR=$SCRATCH
python bin/train.py --dataset dummy --model unetrpp --epochs 1
```
=> fix for running on ecmwf atos gpus

config/datasets/titan_full.json, doc/titan.md, py4cast/datasets/titan/__init__.py
- Fixes Issue #8 
- Removes `dataset` loading mode : leaves only grib and npy file format
- Removes Cyeccodes grib reader and leaves only xarray
- Improves method `conv_npy_and_rescale` that converts gribs to npy for all wanted parameters for training
=> Fix grib reader in Titan

.github/workflows/tests.yml, bin/train.py, py4cast/datasets/base.py, py4cast/datasets/dummy.py, py4cast/datasets/poesy.py, py4cast/datasets/smeagol.py, py4cast/datasets/titan/__init__.py
* Adds a pin_memory_ method to NamedTensor to replace the underlying tensor with a memory pinned copy
* Adds a pin_memory method to our custom Item/ItemBatch (see https://pytorch.org/docs/stable/data.html#memory-pinning)
* Adds a pin_memory arg to the training script
* Makes sure we test it at least once in the CI
=> adds torch's pin_memory support to py4cast

.github/workflows/tests.yml, Dockerfile, README.md, bin/inference.py, bin/train.py, py4cast/datasets/base.py, py4cast/lightning.py, py4cast/models/vision/unetrpp.py, py4cast/observer.py, py4cast/utils.py
* Makes the training system works with both float-32 and bf16
* Adds utility methods to lightning to cast all trainable parameters and also registered buffers
* Adds a env var to force usage of Tri Dao's flash attention as a drop in replacement of torch's scaled_dot_product_attention (useful because the latter works for both f32 and bf16 whereas flash_attn raises if not f1p6 or bf16)
* Adds flash_attn to Dockerfile
* Tested on EWC A100, including inference
Note: I tried to use the lighting features (trainer's precision, init_module context manager) to let it handle automagicaly the conversion but so far it didn't work.
=> Fp16 bf16 support + flash attention from flash_attn

py4cast/datasets/poesy.py
The use of np.memmap changes the data type (need to save the npy files to rbf files before using np.memmap). One solution : replace the np.memmap by np.load with memory mapping mode.
=> fix np.load with memory mapping

bin/train.py, py4cast/lightning.py
The **--no_log** command line flag doesn't work: some plots are still drawn and an Exception is raised :
This PR ensures that when **-no_log** is specified all drawing and logging code is ignored.
```python
wrapper_output = wrapper_module(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
return forward_call(*args, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
else self._run_ddp_forward(*inputs, **kwargs)
File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in …
```
=> Fixes no_log mode by ignoring all plot and log ops

bin/train.py, py4cast/datasets/base.py, py4cast/datasets/titan/__init__.py, py4cast/lightning.py
- Fix memory leak when computing stats by adding an accumulator and a counter to compute means, squares, min and max.
- Titan can now handle different versions of itself : versions are stored in `TITAN_ROOT_DIR/subdatasets/` and named after their config file and grid. For instance `titan_full_PAAROME_1S40_100-612-240-880`
- Parameters stats and time diff stats are now stored in the aforementioned folder and depend on the version of the dataset
- The titan `prepare` command now handles : converting gribs to npy, computing stats and checking chich samples are valid.
=> Refactoring Titan cache dir and preparation + fix memory leak when computing stats

bin/gif_comparison.py, bin/train.py, py4cast/datasets/base.py, py4cast/lightning.py, tests/test_datasets.py
* Improves NamedTensor with index_select_dim and select_dim which maps to underlying torch's index_select and select
* NamedTensor now accept any dimension as the "special" features dimension (constructor argument with a default value of "features"). __getitem__ uses the right dimension
* Added unit tests for new NamedTensor features
* lightning auto-regressive loop is now more explicit and flexible, timestep dim and tensor slicing is no longer hardcoded
* Adds channels_last option (default False)
* Restores simple and advanced profiling options
The advanced profiling saved to a local text file does the job:
=> Improves NamedTensor and make ar loop more expressive and flexible

py4cast/lightning.py
- Add a log file in the same folder as training logs, named `git_log.txt`, which contains info on the last commit and the git status.
Example:
```bash
commit 6f1e238692f6c6651675f4a8da93218c9bfd96ab
Author: colon3ltocard <36170699+colon3ltocard@users.noreply.github.com>
Date:   Thu Oct 3 10:04:23 2024 +0200
prevent shutils.copy in no_log mode (#57)On branch main
Your branch is up to date with 'origin/main'.
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   py4cast/lightning.py
no changes added to commit (use "git add" and
```
=> Add a log file with git commit and status when launching training

py4cast/datasets/base.py, tests/test_datasets.py
* when returning NamedTensor the select_dim and index_select_dim were not preserving the feature dimension attribute, this PR fixes that.
=> preserves feature_dim_name

py4cast/models/vision/unetrpp.py
* in a previous PR I added proj_size as a setting and it was applied to all EPA modules accross the UnetR++ architectures
* I see a slight (0.4) increase in val_loss following this modification, but spectral RMSE are almost identical
* This PR reverts the proj_sizes as per the original implementation and adds dedicated settings for decoder_proj_size (32) and encoder_proj_sizes (64, 64, 64, 32)
=> Restores encoder proj_sizes as per original paper + associated settings

config/datasets/titan_lbc.json, py4cast/datasets/titan/__init__.py
Adding Arpege data to Titan dataset for boundary forcing.
To do that, I will follow those steps :
- Selecting the desired atmespheric parameters, for instance u, v, t, z and hu at levels 250, 500, 700 and 850. Those are defined in the configuration file (titan_lbc.json).
- Converting grib data to npy format.
- Resizing and resampling Arpege data to the Titan dataset size and resolution (Arome 2km, 512 x 640)
=> create config to consider arpege data for lbc

config/models/unetrpp161024_linear_up_manual_4blocks.json, py4cast/models/vision/unetrpp.py, tests/test_models.py
* Make the number of transformer blocks of the encoder and decoder adjustable with the settings
* Provide a settings file for a unetr++ with 4 transformer blocks (instead of default 3)
* Fix lightning unit test (the name of the .ckpt was different on my machine than the hardcoded one, now we just find the first .cktp file)
=> Unetrpp no transformer blocks

py4cast/datasets/__init__.py
Fix bug for Titan inference. 
Cast config_file as a Path instead of a str as intended for from_json argument.
Command:
python bin/inference.py --model_path /scratch/shared/py4cast/logs/camp0/titan/halfunet/sezn_run_dev_41 --date 2023010300 --dataset titan --infer_steps 2
Stack trace:
Traceback (most recent call last):
File "/home/mrmn/seznecc/repository/py4cast/bin/inference.py", line 71, in <module>
dm = PlDataModule(
File "<string>", line 10, in __init__
File "/home/mrmn/seznecc/repository/py4cast/py4cast/lightning.py", line 63, in __post_init__
self.train_ds, self.val_ds, self.test_ds = get_datasets(
File "/home/mrmn/seznecc/repository/py4cast/py4cast/datasets/__init__.py", line 95, in get_datasets
return dataset_kls.from_json(
File …
=> fix bug : config_file type str -> Path

README.md, bin/gif_comparison.py, bin/scores_comparison.py, bin/test.py, py4cast/plots.py
- During test stage, score_cards RMSE are saved as a json in save folder, to be used for the plots
- Add `bin/scores_comparison.py` script to compare RMSE of multiple models on 4 surface parameters.
- Add usage doc in readme
Exemple plot :
=> Add script to compare RSME of multiple models

Dockerfile, README.md, oci-image-build.sh
Modification in order to build the docker image. 
Meteo France users should from now export an env variable to use the meteo-france certificate.
=> Dockerfile correction

bin/train.py, py4cast/lightning.py
- use the `trainer.fit()` to load the checkpoint in case of full training resume
- fix the `Metric.compute()` called before  `Metric.update()`. Ffor any reason that was blocking in restart mode but not starting a training from scratch (even if a warning was displayed `UserWarning: The compute method of metric MetricPSDK was called before the update method which may lead to errors, as metric states have not yet been updated.`)
Solve #98
=> Fix restart from checkpoint

README.md, bin/train.py, py4cast/lightning.py, py4cast/metrics.py, py4cast/plots.py, requirements.txt
This PR resolves #99 with the following additions:
- add the possibility to log with the `MLFlowLogger`, in addition to thre `TensorboardLogger`, using the `--mlflow_log` option of the `bin/train.py` CLI,
- log the trained model in the MLFlow fashion at the final step of `train.py`, if the  `--mlflow_log` option is activated,
- add logging of metrics at the test stage,
- document the MLFlow logger output configuration
=> Add an optional MLFlow logger

README.md, doc/known_issues.md
To resolve #89 , this PR documents in a new `known_issues.md` file, the workaround to install onnxruntime on a CentOS7/RHEL7 machine.
=> Document the workaround to install onnxruntime 

Dockerfile, oci-image-build.sh
* add the possibility to skip crt copy in docker image build, according to the INJECT_MF_CERT value (resolve #95)
* remove manual eccode install from source, while the python package is now standalone
=> Make the Dockerfile less adherent to MF env

py4cast/datasets/base.py
Correct bug of batchItem. The number of input step should be equal of the number of time steps of the input.
=> correct itembatch input step

py4cast/io/outputs.py, py4cast/lightning.py, requirements.txt, tests/test_io.py
See [mfai PR#49](https://github.com/meteofrance/mfai/pull/49) for a detailed description of the NamedTensor changes.
Broadly, methods that had the `bare_tensor` parameter, wich governed wether the return type was `NamedTensor` or `torch.Tensor` have been split into 2 methods. One for each return type.
```python
def select_dim(self, dim_name: str, index: int, bare_tensor: bool = True) -> Union["NamedTensor", torch.Tensor]:
```
becomes
```python
def select_dim(self, dim_name: str) -> "NamedTensor":
def select_tensor_dim(self, dim_name: str) -> torch.Tensor:
```
=> upgrade mfai to commit e6fccce, NamedTensor rework

config/CLI/dataset/titan.yaml, config/CLI/model/customunet.yaml, config/CLI/model/deeplabv3.yaml, config/CLI/model/deeplabv3plus.yaml, config/CLI/model/graphlam.yaml, config/CLI/model/halfunet.yaml, config/CLI/model/hilam.yaml, config/CLI/model/hilamparallel.yaml, config/CLI/model/segformer.yaml, config/CLI/model/swinunetr.yaml, config/CLI/model/unet.yaml, config/CLI/model/unetrpp.yaml, config/CLI/trainer.yaml, py4cast/lightning.py
This PR aims at finding the configuration to reproduce early acceptable experiments. It adresses issue #159.
What changed in this PR:
* added the keyword `obs_step_btw_t0` in order to subsample the validation/test period,
* changed the learning rate scheduler to reuse the former one (from Hugging Face's `transformers`).
Be carefull as now the learning rate and others parameters for the optimizer are in the model config file.
=> Training reproducibility

py4cast/lightning.py
This PR fixes a known limitation of the LightningCLI, hyperparameters and checkpointing.
Lightning saves the init args from the `LightningModule`'s constructor into the checkpoint under `hyper_parameters`. But when one uses `link_arguments(..., apply_on="instantiate")`, the linked arguments are injected **_after_** instantiation. That means that `save_hyperparameters()` does not see these arguments.
One solution is to manually add the linked arguments to the hyperparameters.
This PR fixes issue #157 .
Update: missing arguments are now stored in the `hparams.yaml` file in addition to being saved in the checkpoint.
=> Allowing the use of `load_from_checkpoint` outside the scope of LightningCLI
